# Generated by Django 5.2.1 on 2025-06-09 10:37

from django.db import migrations, models
import uuid


def generate_tokens(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    for booking in Booking.objects.filter(cancellation_token__isnull=True):
        booking.cancellation_token = uuid.uuid4()
        booking.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_cancellation_token'),
    ]

    operations = [
        migrations.RunPython(generate_tokens),
    ]
