# Generated by Django 5.2.1 on 2025-11-02 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_user_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='menu_item',
            field=models.ForeignKey(blank=True, help_text='Optional dish the guest wants to pre-order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.menuitem'),
        ),
    ]
